/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const SettingsLazyRouteImport = createFileRoute('/settings')()
const SearchLazyRouteImport = createFileRoute('/search')()
const ImportLazyRouteImport = createFileRoute('/import')()
const AssetsLazyRouteImport = createFileRoute('/assets')()
const IndexLazyRouteImport = createFileRoute('/')()
const StoriesIndexLazyRouteImport = createFileRoute('/stories/')()
const PeopleIndexLazyRouteImport = createFileRoute('/people/')()
const StoriesIdLazyRouteImport = createFileRoute('/stories/$id')()
const PeopleIdLazyRouteImport = createFileRoute('/people/$id')()

const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const SearchLazyRoute = SearchLazyRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/search.lazy').then((d) => d.Route))
const ImportLazyRoute = ImportLazyRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/import.lazy').then((d) => d.Route))
const AssetsLazyRoute = AssetsLazyRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/assets.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const StoriesIndexLazyRoute = StoriesIndexLazyRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/stories/index.lazy').then((d) => d.Route))
const PeopleIndexLazyRoute = PeopleIndexLazyRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/people/index.lazy').then((d) => d.Route))
const StoriesIdLazyRoute = StoriesIdLazyRouteImport.update({
  id: '/stories/$id',
  path: '/stories/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/stories/$id.lazy').then((d) => d.Route))
const PeopleIdLazyRoute = PeopleIdLazyRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/people/$id.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/assets': typeof AssetsLazyRoute
  '/import': typeof ImportLazyRoute
  '/search': typeof SearchLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/people/$id': typeof PeopleIdLazyRoute
  '/stories/$id': typeof StoriesIdLazyRoute
  '/people/': typeof PeopleIndexLazyRoute
  '/stories/': typeof StoriesIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/assets': typeof AssetsLazyRoute
  '/import': typeof ImportLazyRoute
  '/search': typeof SearchLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/people/$id': typeof PeopleIdLazyRoute
  '/stories/$id': typeof StoriesIdLazyRoute
  '/people': typeof PeopleIndexLazyRoute
  '/stories': typeof StoriesIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/assets': typeof AssetsLazyRoute
  '/import': typeof ImportLazyRoute
  '/search': typeof SearchLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/people/$id': typeof PeopleIdLazyRoute
  '/stories/$id': typeof StoriesIdLazyRoute
  '/people/': typeof PeopleIndexLazyRoute
  '/stories/': typeof StoriesIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/import'
    | '/search'
    | '/settings'
    | '/people/$id'
    | '/stories/$id'
    | '/people/'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/import'
    | '/search'
    | '/settings'
    | '/people/$id'
    | '/stories/$id'
    | '/people'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/import'
    | '/search'
    | '/settings'
    | '/people/$id'
    | '/stories/$id'
    | '/people/'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AssetsLazyRoute: typeof AssetsLazyRoute
  ImportLazyRoute: typeof ImportLazyRoute
  SearchLazyRoute: typeof SearchLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  PeopleIdLazyRoute: typeof PeopleIdLazyRoute
  StoriesIdLazyRoute: typeof StoriesIdLazyRoute
  PeopleIndexLazyRoute: typeof PeopleIndexLazyRoute
  StoriesIndexLazyRoute: typeof StoriesIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$id': {
      id: '/stories/$id'
      path: '/stories/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof StoriesIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AssetsLazyRoute: AssetsLazyRoute,
  ImportLazyRoute: ImportLazyRoute,
  SearchLazyRoute: SearchLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  PeopleIdLazyRoute: PeopleIdLazyRoute,
  StoriesIdLazyRoute: StoriesIdLazyRoute,
  PeopleIndexLazyRoute: PeopleIndexLazyRoute,
  StoriesIndexLazyRoute: StoriesIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
